apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: coredns-pdb
  namespace: kube-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      k8s-app: kube-dns
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kube-vip-pdb
  namespace: kube-system
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: kube-vip
