slack_webhook_url: ""
sops:
    age:
        - recipient: age175q56r04k72n3de8aaanz6dydd5g38qs6gh2shmryvu5x6335vasmmd8e7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnY0RWcnlvV2d4ek04OVJ6
            K2MzRWg2ckNSRnB2Y1ZZRStnYjNRcmswRzNVCnROd2JkZWRMc052V2wwc2FGd1BL
            V0VYeGZRdy9semtKZzVWeDh1UDV5OEkKLS0tIDZ2QWNtbFVxMzg5QjV2R1ZnZklD
            UmJQUXV5OXZtMUJBU3k5WENKWHBFWUUKrvfA8b1Jknip1Mn7YBT24lSpSMF0M27f
            Q+Vpy6dkON8H70wnbVt6PAtct3nJKDbHH6tMbWJH3YW0JT0s8EUGIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T18:15:02Z"
    mac: ENC[AES256_GCM,data:IKdmm6xhLWtTAA5GLTVkRoaEB1XC+BCX0ml+n6liHrv6yCdh0MecXxLFVVGqBE0nn1gLAWMYwEEHkZr0wvXTqDazo4sSMeHJgwQE4UYWY0bSSvMoLrQLqpcws64Vp5yo4g2CN4n4yC2zxuQz47xVRWqMDnLueq/XwdQphYdCcSE=,iv:zQ1JiX6iwWStzGCHN6NW9F7XQz4daCL3kZB0JEKSxNs=,tag:t5sqzg7IQJiHTDqwyf1fzQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
