slack_webhook_url: ENC[AES256_GCM,data:GPwRKtIkbzle/NtxTIhSJUZ1kCMv3llNyizscjtJ/N6VuwEAqM5x+jHpHJ6Ko+qOkiVXoh+c7VO98UVIx+m0CdXQinud7eOkKU9+rX5UlkO+,iv:LCz0BSi8vlHG9JV/eUmf1XXjKn4hF3pySbg5YUX4h/A=,tag:34V2FYveqRuMOY/BnGufIA==,type:str]
sops:
    age:
        - recipient: age175q56r04k72n3de8aaanz6dydd5g38qs6gh2shmryvu5x6335vasmmd8e7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnY0RWcnlvV2d4ek04OVJ6
            K2MzRWg2ckNSRnB2Y1ZZRStnYjNRcmswRzNVCnROd2JkZWRMc052V2wwc2FGd1BL
            V0VYeGZRdy9semtKZzVWeDh1UDV5OEkKLS0tIDZ2QWNtbFVxMzg5QjV2R1ZnZklD
            UmJQUXV5OXZtMUJBU3k5WENKWHBFWUUKrvfA8b1Jknip1Mn7YBT24lSpSMF0M27f
            Q+Vpy6dkON8H70wnbVt6PAtct3nJKDbHH6tMbWJH3YW0JT0s8EUGIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T04:21:57Z"
    mac: ENC[AES256_GCM,data:lw9TtrCWMpFoLQHYXDuwwPcxg12ybiW+yqFFxoY4KjzWkIiRteqL9ExvUbtmWGY9VohFrZBsn8fIOB22rcP/stqyVIAlooVqSOj3HzzkQE+o1uVFLvzJhIsq/W0jzW1g3muybl3NkeF22iqI31C6ckFW0ql5t0qco6AswqnrVQQ=,iv:j7XuWFFtIWWYAxY+7vjSSTvFOy7yTyUkZtSkmaGV8uU=,tag:95J0z3dQ/dpBvIdO4jSsAQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
