grafana:
    adminPassword: ENC[AES256_GCM,data:VoeWayvLQxzTfO4qgNNR1LMDwI9VKGF325ZF6ByTl3Pwp/neg3lfhw==,iv:pCRcfj090C1O4suLeOSUZlloTFqNSJK4Y6+IQG+aMpY=,tag:I5PpatafK89U4x3hgZK5iA==,type:str]
alertmanager:
    config:
        global:
            slack_api_url: ENC[AES256_GCM,data:wDsBhlL/WafJYV/sWn2imBJZgFsiG4aY/g8AWtLVghVdKelAHJf3Bfq2FRJ8vDzAVWjsrjEV+6QVkxM+YI+tln2zYp4X0O56SFY1h3dnR6/t,iv:F36xQVQm8T+55eCZdMol8lEKQh/MuwTyH990b3m6MHw=,tag:NSdOKUMGVC7tquWBPhaCxQ==,type:str]
sops:
    age:
        - recipient: age175q56r04k72n3de8aaanz6dydd5g38qs6gh2shmryvu5x6335vasmmd8e7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsMzcwUEtNNzNhSTNXU1ZI
            Y203VjBpWTdGOFNQVE9vVnVyNHJEMnZOckFNCjFDY0d0cjZHeGZkV0p5QlZxMXR0
            Rk92ditXQlRuTHExSXJOc1FBa2E2WlEKLS0tIFFtV21ENHE2TXg2RTJwdWJWSGFU
            bVNGUTFLZDg5NlNqT3N2ODh2anZjWlEKk1Fv/cAyjnLOUTRV6q1ABWZ4pRXH41dM
            uuJ0Wkhsk2LrXdQLQZ1DOwEJCY00IiJVnX6V+7ZaJYT2Ld9knlmGlw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-26T05:38:21Z"
    mac: ENC[AES256_GCM,data:SQKUpTI5fZoccsUNW8vsZ9TYGm5MsCjyYdZ1P9opm2UpuOph6ZNM8x9x6i4xakii3pHMBSzIPF7LewH6rDC4/PYJ/pEMwNf/bLMnrz3LbHWvNzpP/dOx0PQ4BzWFkG9uSQfAvl7pmHoG5qLBkVn0cnYMDfF4C77xfJAVwRZ1iCs=,iv:Jnmpxg48X7uBKfsRYvxp4Jt9nr8buOtslGZVAu1lDso=,tag:V3hkCwJMcSK/MfccU9uflg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
