alertmanager:
    config:
        global:
            slack_api_url: ENC[AES256_GCM,data:wDsBhlL/WafJYV/sWn2imBJZgFsiG4aY/g8AWtLVghVdKelAHJf3Bfq2FRJ8vDzAVWjsrjEV+6QVkxM+YI+tln2zYp4X0O56SFY1h3dnR6/t,iv:F36xQVQm8T+55eCZdMol8lEKQh/MuwTyH990b3m6MHw=,tag:NSdOKUMGVC7tquWBPhaCxQ==,type:str]
sops:
    age:
        - recipient: age175q56r04k72n3de8aaanz6dydd5g38qs6gh2shmryvu5x6335vasmmd8e7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsMzcwUEtNNzNhSTNXU1ZI
            Y203VjBpWTdGOFNQVE9vVnVyNHJEMnZOckFNCjFDY0d0cjZHeGZkV0p5QlZxMXR0
            Rk92ditXQlRuTHExSXJOc1FBa2E2WlEKLS0tIFFtV21ENHE2TXg2RTJwdWJWSGFU
            bVNGUTFLZDg5NlNqT3N2ODh2anZjWlEKk1Fv/cAyjnLOUTRV6q1ABWZ4pRXH41dM
            uuJ0Wkhsk2LrXdQLQZ1DOwEJCY00IiJVnX6V+7ZaJYT2Ld9knlmGlw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T03:41:17Z"
    mac: ENC[AES256_GCM,data:E0EGDP3N+ESGzlhPMEx9rJPGrCcYsC18sBWVtBkzP1BJLOJh19jNzJ0IVqthAKxUcJ3l8CDVnU7JivX8RiFuZ5OWfQdkkIVTKIODkCbX9im7JzgBpRK37oZzMkgS4duZEVnJXMHsSj6ORVirAi0450ztFOc5ge2EDVTNcKLfuVU=,iv:Pti1B40TBNj/vUUH6gSi5wzi3CU9okXWQWBECtTHZJI=,tag:PGYOl+1OfLHteLvNuHPWvA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
